import type { StackGroup } from "@/lib/types";

export const stackGroups = [
  {
    id: "programming-ai",
    label: "Programming & AI",
    items: [
      "Python",
      "C++",
      "C",
      "Java",
      "MATLAB",
      "LabVIEW",
      "PyTorch",
      "TensorFlow",
      "Keras",
      "CUDA",
      "TensorRT",
      "Hugging Face",
      "Ollama",
      "LangChain",
      "RAG pipelines",
      "FastAPI",
      "Flowise",
      "n8n",
      "OpenWebUI",
      "Docker",
    ],
  },
  {
    id: "platforms-simulation",
    label: "Platforms & Simulation",
    items: [
      "Isaac Sim",
      "Isaac Lab",
      "Gazebo",
      "Simulink",
      "PX4",
      "ArduPilot",
      "DJI",
      "digital twins",
      "synthetic data",
      "sim-to-real",
    ],
  },
  {
    id: "robots-sensors",
    label: "Robots & Sensors",
    items: [
      "Boston Dynamics Spot",
      "Clearpath Husky",
      "Unitree H1/G1",
      "KUKA",
      "Fanuc",
      "Kinova",
      "ST Robotics",
      "LiDAR",
      "radar",
      "thermal cameras",
      "multispectral cameras",
      "motion capture",
      "GNSS",
      "IMUs",
      "3D scanners",
    ],
  },
] satisfies StackGroup[];
